name: Format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format_frontend:
    name: Format Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
        working-directory: ./frontend
      - run: npm run check-ci
        working-directory: ./frontend
  format_backend:
    name: Format Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: pip install --upgrade black==18.9b0
      - run: black . --check --diff