name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions#comment102508135_58034787
      - run: echo ${GITHUB_HEAD_REF#refs/heads/}
      - run: echo ${GITHUB_HEAD_REF}
      - run: echo ${GITHUB_REF#refs/heads/}
      - run: echo ${GITHUB_REF#refs/heads/}
      - run: python3 codalab_service.py build services --pull --version ${GITHUB_HEAD_REF#refs/heads/}
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   strategy:
  #     matrix:
  #       test: [unittest gen-rest-docs gen-cli-docs gen-readthedocs, basic upload1 upload2 upload3, upload4 download refs binary, rm make worksheet worksheet_search, worksheet_tags freeze detach perm, search search_time run read, kill write mimic status, batch resources groups netcat, netcurl anonymous competition unicode, workers rest1 worksheets]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.6
  #     - run: python3 codalab_service.py build services --pull --version master
  #     - run: |
  #         python3 codalab_service.py start --services default monitor --version ${VERSION}
  #         python3 codalab_service.py test --version ${VERSION} ${TEST}
  #         docker restart codalab_worker_1
  #         python3 codalab_service.py test --version ${VERSION} run
  #         docker stop codalab_worker_1
  #         python3 codalab_service.py start --services worker --version ${VERSION} --shared-file-system
  #         python3 codalab_service.py test --version ${VERSION} --shared-file-system ${TEST}
  #       env:
  #         TEST: ${{ matrix.test }}
  #         VERSION: master
  # ui_test:
  #   name: UI Tests
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.6
  #     - run: python3 codalab_service.py build services --pull --version master
  #     - run: |
  #         python3 codalab_service.py start --services default monitor --version master
  #         docker exec -it codalab_rest-server_1 /bin/bash -c "python3 scripts/create_sample_worksheet.py"
  #         python3 tests/ui/ui_tester.py --headless